spring:
  datasource:
    url: jdbc:mysql://rm-2zexq8f5c15k4067pno.mysql.rds.aliyuncs.com:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: whcsfz
    password: whcsfz@123
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
